name: "build-and-pack"
on:
  push:
    branches:
      - main
      - "v*"

permissions:
  contents: write

jobs:
  build:
    env:
      PACKED_JS_PATH: "dist/index.js"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push packed js
        run: |
          if [ -z "$(git status ${{ env.PACKED_JS_PATH }} --porcelain)" ]; then
            echo "${{ env.PACKED_JS_PATH }} is up to date"
            exit 0
          fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack with dependencies to ${{ env.PACKED_JS_PATH }}"
          git push origin HEAD:${{ github.ref_name }}
