name: Test

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mpy-reference: ["v1.22.1", ""]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build and Install MicroPython Unix Port
        uses: ./
        with:
          reference: ${{ matrix.mpy-reference }}

      - name: Verify mpy-cross Installation
        run: mpy-cross --version

      - name: Verify Micropython Installation
        run: micropython tools/print_version.py

      - name: Verify MPY_DIR
        run: |
          echo "MPY_DIR is set to $MPY_DIR"

          if [ -d "$MPY_DIR" ]; then
            echo "The directory $MPY_DIR exists."
          else
            echo "The directory $MPY_DIR does not exist."
            exit 1
          fi
