name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build and Install MicroPython Unix Port
        uses: ./

      - name: Verify mpy-cross Installation
        run: mpy-cross --version

      - name: Verify Micropython Installation
        run: micropython tools/print_version.py

      - name: Verify MPY_DIR
        run: |
          echo "MPY_DIR is set to $MPY_DIR"

          if [ -d "$MPY_DIR" ]; then
            echo "The directory $MPY_DIR exists."
          else
            echo "The directory $MPY_DIR does not exist."
            exit 1
          fi
